---
title: "edX Linux"
output: 
  html_document: 
    theme: journal
    toc: yes
---

## Introduction
This comes from the [edX class](https://courses.edx.org/courses/course-v1:LinuxFoundationX+LFS101x.2+1T2015/courseware)

List of commands
1. `apt` - advanced package tool

The main sources of information
1. Man pages
2. Command help
3. GNU info
4. Other
5. [https://www.gentoo.org/doc/en/](https://www.gentoo.org/doc/en/)

### Man pages
Various options
1. `-f` will display all files that contain the word in the argument
2. `-k` will display all discussion even if the word is not used

Man pages are divided into 9 chapters. The chapter number can be forced by the number.  The `a` parameter will display all manual pages with the given name.
* `man 3 printf`
* `man -a printf`

###GNU information system
This is more free-form and open to linkages. 

Typing `info` with no arguments in the command line gives a list of topics. `info <topic name` will give information on the topic. To negotiate the page
* q will quite
* h will help
* enter to select
* n go to next node
* p go to previous node
* u one node in the index

### Help command
Will tend to provide short information.  For example, to find out about manual `man --help`

###Other
`gnome help` will provide specific help about the particular Linux family. 

##Command line
`X Window` can be turned off. There are 7 `virtual terminals`.  Access by `CTRL-ALT-F6`

Usually there are three components: command, options and arguments.  Options are switches or modifiers. Use `sudo service gdm stop` to stop the desktop manager.

###Basic operations
* cd
* cat
* echo
* ls
* rmdir
* man
* exit
* login
* mkdir

Best to shut-down with `shutdown`, the `init` process will control the shutting down. `shutdown -r` will reboot. Usually, executable programmes are in `/bin/usr/bin/` to find where programmes are use `which <prog>` or `whereis <prog>`.  

###Utilities
* `cd ~` move to home directory
* `cd ..` move to parent
* `cd - ` move to previous directory

###Explore 
* `cd/` Change to root directory
* `ls` list files and directories
* `ls -a ` list all files (including hidden)
* `tree` view of file system
* `ln` can create soft or hard links

Move directories to the stack with `pushd .` to move to that first entry in the stack type `pop`.  However, it is best to use `pushd +1` for the first element and `pushd + 2` for the second element.  This will preserve the stack, while `pop` will clear.  Look [here](http://www.eriwen.com/bash/pushd-and-popd/)

###Standard file streams
* standard input `stdin`
* standard output `stdout`
* standard error `stderr`
* pipe can direct output to a new input

###I/O direction
* `do_something < input_file`
* `do_something > output_file`
* `|` pipe moves inputs to outputs
* `locate` will search for files
* `grep` can be used to filer files
* `locate` uses the `updatedb` programme.  This can be run once a day but can be initiated 
at any time
* `find` will find from current directory. `-name` will find only particular name, `-type` will find only particular type.
** `find -name ".swp" -exec rm {} ':'` will remove all the files with swp extension by sending them to {} to have rm executed on them.
* `-exec` is s modification that will allow you to execute commands on the result of the `find`

###Matching files
* `?` match any singe character
* `*` match string of characters
* `[set]` match characters.  
* `[!set]` match not characters
* `-ctime` time file was created
* `-atime` time file was accessed
* `-mtime` time files was modified

###Working with files
* `cat` view short files and link together
* `tac` look file backwards
* `less` view larger file with paging programme (use / to search)
* `tail` print last 10 lines. 
* `head`
* `touch` will modify the file's timestamps to the current time.  Can also be used to create a new file. 
* `rm` will remove a file `-i` interactive will ask for confirmation for each file. 

##Package management
The Debian family has two levels of package management: the low level `dpkg` and the high level `apt-get`. The high level tool will mostly call the low level tool when needed. This is *advanced-package-tools*. 

### Operations
* install package: `dpkg --install foo.deb`
* install package dependencies: `apt-get install foo`
* remove package: `dpkg --remove foo.deb`
* remove package dependencies: `apt-get autoremove foo`
* update package: `dpkg --install foo.deb`
* update package and dependencies: `apt-get install foo`
* Update entire system: `apt-get dist-upgrade`
* Show all installed packages: `dpkg --list`
* Get information on package: `dpkg --listfiles foo`
* Show packages named foo: `apt-cache serach foo`
* Show all available packages: `apt-cache dumpavail foo`
* What package is file part of: dpkg --search file`

### User environment
Identify who is logged on with `who`. To identify the current user ``whoami`. `who -a`  gives more details. 

Control of groups is managed through the `/etc/group` file. 

`useradd` will add a new user. `userdel` will remove a user. Use the `-r` option to remove the home directory.

`id` gives user info. 

`su` substitute or switch user. `sudo` super user. Configuration files are in `etc/sudoers`and `etc/sudoers.d` directory. 

First the `/etc/profile` is read and then the following files are searched 

* `~/.bash/profile`
* `~/.bssh/bash_login`
* `~/.profile`

###Environmental variables
Some can be set by the user. An environment variable is a character string that contains information that is used by an application. `set`, `env` and `export` are the ways to view the environment variable. 

The `PATH` is an ordered list of directories that will be scanned when a command is given. A null directory or `./` is the current directory. 

**Prompt Statement** is used to customise the prompt string. `PS1` is the primary prompt variable. Changes

* `\u~` User name
* `\h~` host name
* `\w~` current working directory
* `\!~` History number of command
* `\d~` Date

### Command history
This is kept in `~/.bash_histry`.  It is possible to use `!!` or bang-bang to execute previous command. `CTRL-R` search history. 

Keyboard short cuts

* CTRL-L: Clears the screen
* CTRL-D: Exits current shell
* CTRL-Z: Puts current process in suspended background
* CTRL-C: Kills current process
* CTRL-H: Same as backspace
* CTRL-A: Goes to the beginning of the line
* CTRL-W: Deletes the word before the cursor
* CTRL-U: Deletes from beginning of line to cursor
* CTRL-E: Goes to the end of the line
* Tab: Auto complete

Changes to file ownership. 

* `chown` change user ownership
* `chgrp` change group ownership
* `chmod` modify owner, user or group

The codes for permissions
 
* 4 for read
* 2 for write
* 1 for execute

So 6 for read and write

`chmod 755 test1` would read and execute access to all and read, write and execute access to owner. 

## Networking

Devices in a network need a unique network address identifier.  This is known as IP (Internet protocol address). Bit-size packets with data buffers and headers are exchanged. There are two types of IP address

* IPv4: uses 32 bits.  Divided into 4 8-bit sections called *octets*. 
* IPv6: uses 128 bits. 

There are five classes of network address:  A, B and C have two components: Network address (Net ID) and Host address (Host ID).  D is for special multicast and E is reserved for future use. 

* Class A uses the first octet as the Net ID and the rest as Host ID. The first bit of the first Octet is set to zero and 000000 and 111111 are reserved, so there are only 126 Class A networks available.  Each class A network can have up to 16.7 million hosts.  The range of host addresses is from 1.0.0.0 to 127.255.255.255 (note the value of an octet or 8-bits can range from 0 to 255)

* Class B address use the first two octets as their Net ID and the last two as the Host ID. The first two digits of the first octet are always 1,0 so there is maximum of 16,384 (4 bits) Class B networks.  The first octet runs from 128 to 191 so the range of host addresses is 128.0.0.0 to 191.255.255.255.

* Class C addresses use the first three octets. The first two digits are 110.  The first octet has values from 192 to 223.  They range from 192.0.0.0 to 223.255.255.255

IP addresses can be signed manually or dynamically. The Dynamic Host Configuration Protocol (DHCP) is used to assign IP addresses. **ipcal** can be used to calculate manual IP address.  

**Name Resolution** is used to convert numerical IP address values to human-readable format known as **hostname**. For example, 140.211.169.4 is the numerical IP address for **linuxfondation.org**.  The **localhost** is associated with the IP address 127.0.0.1 and describes the machine that you are on. 

`cat /etc/hosts` will give the contents of the `cat/etc/resolv.conf`.  To look up hosts `host linuxfoundation.org` will display the IP address for linuxfoundation. 
***Network interfaces**
These are connection channels between a device and a network. Physically, the proceed through a network interface card(NIC). `ifconfig` command will report interfaces.  Network configuration files will ensure that the interfaces function correctly.  These will be in `/etc/network/interfaces/`.   `/etc/init.d/networkingstart` will start networking configuration. To view the IP address, `/sbin/ip addr show`.   To view routing information, `/sbin/ip route show`

`ping <hostname>` will check whether a host can receive and broadcast data.

###Routing
A network has nodes and the **routing tables** show the IP address of each node as well as the *IP routing protocols*. Use `route -n` to see table. 

## Networking tools

* `ethtool` queries network interfaces and set parameters. 
* `netstat` shows the active connections and data
* `nmap` scans open ports
* `tcpdump` dumps network traffic for analysis
* `iptraf` monitors network traffic. 

## Browsers
Download without using a browser.  Use `wget`

* Large files
* Recursive downloads (one refers to another)
* Password required 
* Multiple file download

Use `wget <url>` will read page as a local file.

Use `curl` to get URL information. It can also allow saving of page contents. Use `curl -c saved.html http://www.mysite.com` will save the contents of mysite to saved.html. 

## Transfering files
File transfer protocol: ftp. Client-server model uses a server and a number of clients. 

Command line ftp clients

* ftp
* sftp: uses secure shell (ssh).  Encrypts data but does not work with anonymous clients like ftp.
* ncftp
* yafc

`ftp -p aristotle.learningmate.com` will make connection, ask for username and password and make the link.  To look at files and transfer use `ls` and `get`. 

**secure shell (SSH)** is used for secure data communication. To run `my_command` on remote system via SSH, use `ssh <remote system? my_command`.  You may be asked for a password but this may also be overridden. 

Files can be moved using **secured copy (scp)**.  To copy a local file to a remote system, `scp <local file> <user@remotesystem>:/home/user`

###Manipulating text

* `cat filename` 
* `cat file1 file2` brings together two files
* `cat file1 file2 > newfile>` put together in new file
* `cat file1 file2 >> newfile>` append
* `cat > file` any subsequent lines go into the file (until CNTR=D is pressed)
* `cat >> file` appended until control-D
* `tac` will print lines backwards
* `echo` will print to screen or file
* `echo >> file1` will append to file 1. 
* `echo` with switch `-e` will allow `\n` newlines and `\t` tabs

Use `sed` as one text editor. 

* `sed -e command < filename`
* `sed -f scriptfile < filename`
* `sed s/pattern/replace_string/ file` replaces first instance of patter with replace_string
* `sed s/pattern/replace_string/ file/g` same but all instances
* `1,3s/pattern/replace_string/ file/g` same but only lines 1 to 3
* `-i s/pattern/replace_string/ file/g` same but same but save changes
* `-i s/pattern/replace_string/ file/g file1 > file2` same but safer because changes can be inspected before deletion of old file

Use `awk` to extract specific contents of a file. 
* `awk 'command' var=value file` specify a command at the command line
* `awk -f scriptfile var=value file` specify a script file
* `awk '{ print $0 }' /etc/passwd` print entire file
* `awk -F: '{ print $1 }' /etc/passwd` Print first field (column) of every line
* `awk -F: '{ print $1 $6}' /etc/passwd` Print first and sixth field of every line


##File management
File manipulation programmes
* `sort` Arrange lines of text according to the sort key. `-u` will sort only unique.
* `uniq` Remove duplicate lines.  Must be consecutive (therefore run sort first).  `uniq -c` will count the duplicate lines 
* `paste` joins two files together. `-d` specifies the delimiters; delimiters can be "space", "tab", "|" etc;`-s` append rather than horizontal join.
* `join` joins two files based on a common field. 
* `split` will split a file into equal size segments. This will leave the original file and will break into 1000 line segments. 

###Regular expressions
* (dot) Match any single character
* a|z Match a or z
* $ Match end of string
* * Match preceding item 0 or more times

Example: "The quick brown fox jumped over the lazy dog"

* a.. matches "azy"
* b.|j. matches both "br" and "ju"
* ..$ matches "og"
* l.*y matches "lazy""
* the.* matches the whole sentence. 

###`grep`
Text searching tool

* `grep [pattern] <filename>` prints all lines with matching pattern
* `grep -v [pattern] <filename>` prints all lines without the pattern
* `grep [0-9] <filename>` prints all lines with numbers 0 to 9
* `grep -C 3 [pattern] <filename>` prints context of lines matching pattern.  Here three lines above and below.

###`tr`
Used for translating one character for another

`tr [options] set1 set2`
One or two options are required.  Will substitute set2 for set1. 

* `cat city | tr a-z A-Z` will translate all the lower case letters in city to upper case
* `tr '{}' '[]' <inputfile> <outputfile>` changes braces to parenthesis
* `tee` takes output from a command and sends it to a file
* `wc` counts `-l` lines, `-w` words or `-c` bytes
* `cut` can extract a specific column. It assumes that columns are separated by a tab

###Large files
These can be loaded using `less` this does not put it into memory.

* `less <filename>`
* `cat <filename> less`
* `head` shows the first few lines
* `tail -n 14` last 14 lines.

### Zip files
* `zcat compressed-file.txt.gz` To view compressed file
* `zless <filename>` or `zmore <filename>` to page through zip
* `zgrep` search inside zip
* `zdiff` find differences in file.

# Printing
Linux standard for printing is **Common UNIX printing system** (CUPS). 

* Scheduler: Manages the print jobs.  
* Configuration:  scheduler reads configuration files. The most important are **cupsd.conf** (mostly for security and access rights) and **printers.conf**. These are stored in `/etc/cups/`.  
* `ip` or `ipr` commands can be used to print from the command line
* `ip <filename>` prints file.
* `ip -d printer <filemame>` prints to a specific printer
* `programme | lp echo string | lp` prints the output of a programme
* `lpq -a` show the queue status
* `lpaadmin` configure queue status

# Introduction to scripts
Use shell scripts.  Most common is *bash*.  Shell is a **commanline interpreter**.  

`#!/bin/bash`
`find. -name "*.c" -ls`

The command interpreter will execute statements that are found in the script. Interpreters

* `/usr/bin/perl`
* `/bin/bash`
* `/bin/csh`
* `/usr/bin/python`
* `/bin/sh`

Choices are listed in `/etc/shells`.  The default is bash. This can be overridden. 

`bash <script>` will send the script file to the shell interpreter. 

## Special characters
* # used for comments
* \ used to continue on to next line
* ; to have a second command on same line
* $ indicates that what follows is a variable
* joining commands wit && will stop subsequent actions when one fails
* joining commands with || will continue until one command succeeds

###Functions

* Declare a function 
* Call a function

syntax
```
function_name () {
  command ...
}
```
arguments that are passed to the function are usually named $1 and $2 etc. 

```
#!bin/bash
display() {
  echo "This is a message from the function"
  echo "The parameter passed from the calling process is" $1
}
display "Bob"
```

###Commands can be divided into the following categories
* Compiled applications: binary executable files that are on the file system. The shell script always has access to things like `rm`, `ls`, `df`, `vi`, `gzip`. 
* Built in **bash** commands: built-in bash commands that can be used in the shell. These include `cd`, `pwd`, `read`, `logout`, `printf`, `let`. A complete list is found on `bash man`. 
* Other scripts

###Command substitution
Sometimes it is necessary to substitute the result of a command to the input of another command. There are two methods

* Enclosing the inner command with back ticks (`)
* Enclosing the inner command in $

Example 
`cd /lib/modules/$(uname -r)/`
The output of the command `umame -r` becomes the argument for cd. 

###Environemnt variables
Environment variables supply inputs, validation and control behaviour. A list of environment variables is found with `env`, `set` and `printenv` commands. 

`$HOME` shows the HOME environment variable, 
`MYCOLOR=blue` sets the MYCOLOR environment variable as blue. 

###Exporting variables
Variables that are created are only available to that script.  To make them more widely available, they must be promoted to **environment variables** using the `export` command. 

Example
`export VAR=value` or `VAR=value; export VAR`

###Script parameters
It is often necessary to pass parameter values to a script. Within a script, the parameter or an argument is represented by $ and a number. 

* $0 is the script name
* $1 the first parameter
* $2, $3 second and third parameters
* $* all the parameters
* $# number of arguments

For example, 
```
#!/bin/bash
echo "The name of the script is:" $0
echo "The name of the first argument is" $1
echo "The name of the second argument is:" $2
```

###Output redirection
The character `>` is used to write the output of a file to another file.  `free > /tmp/free.out` will send the output of fee to the free-out file. `>>` will append the file. 

###Input redirection
Just as output can be redirected, input can be taken from another file. The `<` is used for input. 

```
#!/bin/bash
echo "Line Count"
wc -l < /temp/free.cut
```
will count the lines in free.cut

## Constructs
The if statement will be based on numeric or string comparisons, truth or failure and file existence. 

```
if condition
then
  statement
else
  statement
fi
```
for example, 
```
if [-f /etc/passwd]
then
  echo "/etcpassed exists"
fi
```
List of things that could be checked

* `-a file` does file exist
* `-d file` is file a directory
* `-f file` is it a regular file (not symbolic link)
* `s file` is it of non-zero size
* `g file` has sgid set?
* `-u file` has suid set?
* `-r file` is file readable
* `-w file` is file writeable
* `x file` is it executable

`man l test` will give the full list

Numerical tests

* `-eq` equal to
* `-ne` not equal to
* `-gt` greater than 
* `-lt` less than 
* `-ge` greater or equal than
* `-le` less of equal to

#Advanced bash scripting
##String manipulation
Basic string operations

* [[ strin1 > string2 ]] compares the sorting order of string1 and string2
* [[string 1 == string 2]] compare characters in two strings
* myLen1={#string1} saves the length of string1 in variable myLen1

##Boolean expressions

* && AND only if both conditions are true
* || OR only is one of the conditions is true
* | NOT only if condition is false

##The case statement
Can be used as an alternative to if statements and can simplify code. The basic structure is 

`
case expression in 
  pattern1) execute commands;;
  pattern2) execute commands;;
  pattern3) execute commands;;
  * ) execute some default commands or nothing
;;
esac
`
For example, 

```
#!/bin/sh
# Prompt user to enter a character
echo "Please enter a letter:"
read charac
case "$charac" in 
  "a"|"A" echo "You have typed a vowel" ;;
  "e"|"E" echo "You have typed a vowel" ;;
  "i"|"I" echo "You have typed a vowel" ;;
  "o"|"O" echo "You have typed a vowel" ;;
  "u"|"U" echo "You have typed a vowel" ;;
  *)    echo "You have typed a consonant" ;;
esac
exit 0
```
###Loops
There are three types of loop

* for
* while
* until

###Script debugging
This can be stated with the command
`bash -x ./script_file` 

Debugging can be set in the script with `set -x .. set +x`

###Redirecting errors to file and screen

There are three file streams

* stdin standard input from the keyboard
* stout standard output (default screen)
* stderr standard error, where messages go

# Processes
Types of process

* Interactive:  started by user (usually bash or Firefox etc)
* Batch process: Automatic or scheduled (FIFO). updatedb
* Daemons: server processes that run continuously. (httpd, xinetd, sshd)
* Threads: Lightweight processes.  (genome-terminal, firefox)
* Kernel threads:  Moving a thread from one part of CPU to another, ensuring that input, output processes have been completed. 

The **scheduler** will manage the **run queue** moving processes into and out of the CPU.  Each process has a process id (**PID**). The person starting the process is identified with the Real User ID (**RUID**).  Only one process can be run at at time.  Processes have a priority. Priority is set by **nicevalue**.  These run from -20 (highest priority) to 19 (lowest priority). 

`ps` provides information about currently running processes. A repetitive update is supplied by `top` or `htop` or `atop`. There are a large number of options for `ps`. `ps -ef` will show all the processes.  

`pstree` shows all the processes running on the system as a tree diagram. To terminate a process `kill -SIGKILL <pid>` or `kill -9 <pid>`.  

###top
* first line of `top` summary of what is happening, how long running, how many users, load average. Load average of 1.0 is fully subscribed but not over-loaded. * second line of `top`:  total number of processes, number running, stopped and zombied. 
* third line: how CPU is being divided between users (us) and system (sy).  
* Fourth and Fifth: show memory usage (RAM - line 4) and swap space (5). Swapping onto the hard drive slows things down. 

Keys an be used to change `top` behaviour. 

* t display or hide information (lines 2 or 3)
* m display or hide information (lines 4 or 5)
* A Sort processes by top resource consumers
* r renice (change priority)
* k kill specific process
* f enter top configuration screen
* c interactively enter a new sort order. 

###Load average
**Load average** is the average of the **load number**. It can be obtained by running `top`, `w` or `uptime`.  

There are three numbers 

* Average load of the system (past minute) as percentage. 
* Utilisation for the past 5 minutes
* Utilisation for the last 15 minutes

The figure can be more than 100\%.  There may be more than one CPU. Jobs can be run in the foreground or background.  A job is just a command launched from the terminal window.  Background jobs have lower priority.  This is useful if they are going to take a long time. `bg` will run in background, `bf` will run in the foreground.  `CNTR-Z` will suspend a job, `CNTR-C` will terminate a job. 

The `jobs` utility will display the jobs running in the background. `jobs -l` provides information about the jobs. 

###Future scheduling
`at` utility can exercise a command in the future. For example `at now + 2 days` will do something in two days time. Use `CNTR-D` to process. 

##Cron
`cron` is a time-based scheduling utility. It is driven by a configuration file `/etc/crontab`. `contab -e` will open the editor. 

There are 6 fields

* MIN: Minutes: 0:59
* HOUR: Hour 0 to 23
* DOM: day of month (1-31)
* MON: month (1-12)
* DOW: day of week (0-6 with 0 = Sunday)
* CMD: Command (Any command to be executed)

For example `******/usr/local/execute/script.sh` will schedule a script to be run every minute. 

`sleep` can suspend a device for a specific time. This can be seconds (s), minutes (m), hours (h) or days (d). `at` will start an application at a later date.  

###Common Applications
##Internet
Firefox and chromium are the main browsers. 

Email applications
* Internet Message Access Protocol (IMAP)
* Post office Protocol (POP)

